apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: yolo-ecommerce
    component: backend
  annotations:
    # Links the service to our BackendConfig
    cloud.google.com/backend-config: '{"default": "backend-health-check"}'
spec:
  type: ClusterIP
  selector:
    app: oscar-yolo-backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000