apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: yolo-ecommerce
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oscar-yolo-backend
  template:
    metadata:
      labels:
        app: oscar-yolo-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: oscar066/oscar-yolo-backend:v1.1.1
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: "mongodb://mongo-service:27017/yolomy"