apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: yolo-ecommerce
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oscar-yolo-client
  template:
    metadata:
      labels:
        app: oscar-yolo-client
        component: frontend
    spec:
      containers:
      - name: client
        image: oscar066/oscar-yolo-client:v1.2.0
        ports:
        - containerPort: 80