# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: mongo-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce # This volume can be mounted as read-write by a single node
#   resources:
#     requests:
#       storage: 1Gi # Requesting 1 Gibibyte of storage